name: build-and-publish
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    environment: prod
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    env:
      APP_DIR: ${{ secrets.APP_DIR }}
      VENV_PY: ${{ secrets.VENV_PY }}
      DJANGO_SETTINGS_MODULE: ${{ secrets.DJANGO_SETTINGS_MODULE }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      REMOTE_HOST: ${{ secrets.REMOTE_HOST }}

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Install snapcraft
        run: sudo snap install snapcraft --classic

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.TOKEN }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
